# Generated by Django 4.2 on 2023-04-20 12:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(choices=[('', 'Select Car Brand'), ('toyota', 'toyota'), ('benz', 'benz')], default='', max_length=10, verbose_name='car_brand')),
                ('plate_number', models.CharField(max_length=12)),
                ('vehicle_insurance', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destitation', models.CharField(max_length=250)),
                ('created_request', models.DateTimeField()),
                ('status', models.CharField(choices=[('', 'Select status'), ('pending', 'pending'), ('done', 'done')], default='', max_length=10, verbose_name='STATUS')),
                ('ClientProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.clientproperty')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distance', models.FloatField()),
                ('cost_per_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.clientrequest')),
            ],
        ),
        migrations.CreateModel(
            name='UmusareRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=10, verbose_name='Gender')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='Phone Number')),
                ('bank_account', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Bank_Account')),
                ('age', models.CharField(max_length=10, verbose_name='Age')),
                ('national_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='National Id')),
                ('driving_license_category', models.CharField(max_length=10, verbose_name='Category')),
                ('profile_image', models.ImageField(upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf'])], verbose_name='Profile Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UmusareWage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('', 'Select status'), ('pending', 'pending'), ('payed', 'payed')], default='', max_length=10, verbose_name='STATUS')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SafeRide.umusarerider')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SafeRide.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.umusarerider'),
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.task')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='Phone Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='Clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.clients'),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='UmusareRider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.umusarerider'),
        ),
        migrations.AddField(
            model_name='clientproperty',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SafeRide.clients'),
        ),
    ]
