# Generated by Django 4.2 on 2023-05-02 15:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50)),
                ('car_type', models.CharField(choices=[('', 'Select car_propery'), ('automatic', 'automatic'), ('manual', 'manual')], default='', max_length=10, verbose_name='car_type')),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destitation', models.CharField(max_length=250)),
                ('created_request', models.DateTimeField()),
                ('status', models.CharField(choices=[('', 'Select status'), ('pending', 'pending'), ('confirmed', 'confirmed')], default='pending', max_length=10, verbose_name='STATUS')),
                ('ClientProperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.clientproperty')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('', 'Select status'), ('pending', 'pending'), ('complete', 'complete')], default='pending', max_length=20)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.clientrequest')),
            ],
        ),
        migrations.CreateModel(
            name='UmusareRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('bank_account', models.CharField(blank=True, max_length=100, verbose_name='Bank_Account')),
                ('driving_license_category', models.CharField(max_length=10, verbose_name='Category')),
                ('profile_image', models.ImageField(upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['.png', '.jpg', '.jpeg', '.pdf'])], verbose_name='Profile Picture')),
                ('driving_license', models.ImageField(upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['.png', '.jpg', '.jpeg', '.pdf'])], verbose_name='driving_license')),
                ('national_id', models.ImageField(upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['.png', '.jpg', '.jpeg', '.pdf'])], verbose_name='national_id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UmusareWage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('', 'Select status'), ('pending', 'pending'), ('payed', 'payed')], default='pending', max_length=10, verbose_name='STATUS')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wages', to='SafeRide.umusarerider')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SafeRide.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='SafeRide.umusarerider'),
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
                ('starting_point', models.DateTimeField()),
                ('ending_point', models.DateTimeField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='SafeRide.task')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='Clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='SafeRide.clients'),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='UmusareRider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to='SafeRide.umusarerider'),
        ),
        migrations.AddField(
            model_name='clientproperty',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_vehicles', to='SafeRide.clients'),
        ),
    ]
