# Generated by Django 4.2 on 2023-04-26 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=50, verbose_name='car_brand')),
                ('plate_number', models.CharField(max_length=50)),
                ('vehicle_insurance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destitation', models.CharField(max_length=250)),
                ('created_request', models.DateTimeField()),
                ('status', models.CharField(choices=[('', 'Select status'), ('pending', 'pending'), ('done', 'done')], default='', max_length=10, verbose_name='STATUS')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=250, unique=True, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distance', models.FloatField()),
                ('cost_per_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UmusareRider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Phone Number')),
                ('bank_account', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Bank_Account')),
                ('driving_license_category', models.CharField(max_length=10, verbose_name='Category')),
                ('profile_image', models.ImageField(upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf'])], verbose_name='Profile Picture')),
                ('driving_license', models.ImageField(upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf'])], verbose_name='driving_license')),
                ('national_id', models.ImageField(upload_to='profile', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf'])], verbose_name='national_id')),
            ],
        ),
        migrations.CreateModel(
            name='UmusareWage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('', 'Select status'), ('pending', 'pending'), ('payed', 'payed')], default='', max_length=10, verbose_name='STATUS')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SafeRide.umusarerider')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SafeRide.task')),
            ],
        ),
    ]
