# Generated by Django 4.2 on 2023-04-26 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SafeRide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='umusarerider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='task',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.clientrequest'),
        ),
        migrations.AddField(
            model_name='task',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.umusarerider'),
        ),
        migrations.AddField(
            model_name='journey',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.task'),
        ),
        migrations.AddField(
            model_name='clients',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='ClientProperty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.clientproperty'),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='Clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.clients'),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='UmusareRider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.umusarerider'),
        ),
        migrations.AddField(
            model_name='clientproperty',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SafeRide.clients'),
        ),
    ]
