# Generated by Django 4.2 on 2023-04-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SafeRide', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproperty',
            name='Client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.clients'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='umusarerider',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bank_Account'),
        ),
        migrations.AlterField(
            model_name='umusarerider',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='umusarewage',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SafeRide.umusarerider'),
        ),
    ]
